services:
  pyroscope:
    image: "pyroscope/pyroscope:latest"
    restart: unless-stopped
    ports:
      - "4040:4040"
    command:
      - "server"
  prometheus:
    image: "prom/prometheus"
    restart: unless-stopped
    volumes:
      - /home/salami/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
  ircd:
    restart: on-failure
    build: .
    ports:
      - "0.0.0.0:6667:6667"
      - "2112:2112"
volumes:
  prometheus_data:
    external: false