services:
  prometheus:
    image: "prom/prometheus"
    restart: unless-stopped
    volumes:
      - ~/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
  ircd:
    image: ircd:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:6667:6667"
      - "2112:2112"
    environment:
      - SERVER_NAME=ircd
      - PROMETHEUS_ENABLE=yes
volumes:
  prometheus_data:
    external: false
