services:
  prometheus:
    image: "prom/prometheus"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
  ircd:
    image: ircd:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:6667:6667"
      - "0.0.0.0:6697:6697"
      - "2112:2112"
    environment:
      - SERVER_NAME=ircd.network.fqdn
      - SERVER_VERSION=0.1
      - PORT=6667
      - PORT_TLS=6697
      - PROMETHEUS=true
      - TLS=true
      - TLS_CERTIFICATE=/app/tls/server.crt
      - TLS_KEY=/app/tls/server.key
volumes:
  prometheus_data:
    external: false
